import type { Program } from '@/lib/types';

export const alexProgram: Omit<Program, 'id'> = {
  name: 'Alex Upper/Lower Hypertrophy Block',
  cycleLengthDays: 7,
  splitType: 'Upper / Lower',
  isActive: true,
  startDate: new Date().toISOString().split('T')[0],
  sessions: [
    {
      dayNumber: 1,
      name: 'Upper A — Push Focus',
      type: 'lift',
      exercises: [
        { exerciseId: 'barbell-bench',   name: 'Barbell Bench Press',   sets: 4, reps: '6–8',  rest: 120, isKPI: true, notes: 'Top set + 3 back-off sets. Add weight when all sets hit 8 reps.' },
        { exerciseId: 'incline-db',      name: 'Incline DB Press',      sets: 3, reps: '10–12', rest: 90, notes: 'Control the negative (3 sec). Chest stretch at bottom.' },
        { exerciseId: 'db-ohp',          name: 'DB Overhead Press',     sets: 3, reps: '10–12', rest: 90, notes: 'Seated or standing. Full range.' },
        { exerciseId: 'cable-fly',       name: 'Cable Crossover / Fly', sets: 3, reps: '12–15', rest: 60, notes: 'Squeeze at peak contraction.' },
        { exerciseId: 'tricep-pushdown', name: 'Tricep Pushdown',       sets: 3, reps: '12–15', rest: 60, notes: 'Superset with lateral raise if pressed for time.' },
        { exerciseId: 'lateral-raise',   name: 'Lateral Raise',         sets: 4, reps: '15–20', rest: 45, notes: 'Light weight, high quality. No swinging.' },
      ],
      notes: 'Push session. Prioritise chest and shoulder pressing quality.',
    },
    {
      dayNumber: 2,
      name: 'Lower A — Squat Focus',
      type: 'lift',
      exercises: [
        { exerciseId: 'barbell-squat',   name: 'Barbell Back Squat',    sets: 4, reps: '6–8',  rest: 150, isKPI: true, notes: 'Belt on working sets. Break parallel. Progress weekly.' },
        { exerciseId: 'romanian-dl',     name: 'Romanian Deadlift',     sets: 3, reps: '10–12', rest: 90, notes: 'Feel the hamstring stretch. Don\'t lock out at top.' },
        { exerciseId: 'leg-press',       name: 'Leg Press',             sets: 3, reps: '12–15', rest: 75, notes: 'Full range, feet shoulder width.' },
        { exerciseId: 'leg-curl',        name: 'Lying Leg Curl',        sets: 3, reps: '12–15', rest: 60, notes: 'Pause at peak contraction.' },
        { exerciseId: 'calf-raise',      name: 'Standing Calf Raise',   sets: 4, reps: '15–20', rest: 45, notes: 'Full stretch at bottom. Slow tempo.' },
      ],
      notes: 'Squat-dominant lower. Primary quad focus.',
    },
    {
      dayNumber: 3,
      name: 'Rest / Cardio',
      type: 'cardio',
      cardio: { type: 'Walk or easy bike', duration: 30, note: 'Optional. Keep HR low. Active recovery.' },
      mobility: ['hips', 'thoracic spine'],
      notes: 'Full rest or 20–30 min easy cardio. No intensity.',
    },
    {
      dayNumber: 4,
      name: 'Upper B — Pull Focus',
      type: 'lift',
      exercises: [
        { exerciseId: 'weighted-pullup', name: 'Weighted Pull-Up',      sets: 4, reps: '6–8',  rest: 120, isKPI: true, notes: 'Add weight when all sets hit 8 reps. Use band if needed.' },
        { exerciseId: 'barbell-row',     name: 'Barbell Row',           sets: 3, reps: '8–10', rest: 90, notes: 'Controlled. Chest stays up.' },
        { exerciseId: 'seated-cable-row',name: 'Seated Cable Row',      sets: 3, reps: '12–15', rest: 75, notes: 'Full stretch and full contraction.' },
        { exerciseId: 'face-pull',       name: 'Face Pull',             sets: 3, reps: '15–20', rest: 45, notes: 'External rotation. High rep, light weight.' },
        { exerciseId: 'incline-curl',    name: 'Incline DB Curl',       sets: 3, reps: '12–15', rest: 60, notes: 'Full stretch at bottom.' },
        { exerciseId: 'hammer-curl',     name: 'Hammer Curl',           sets: 3, reps: '12–15', rest: 45, notes: 'Supinate at top for full contraction.' },
      ],
      notes: 'Pull session. Back thickness and biceps focus.',
    },
    {
      dayNumber: 5,
      name: 'Lower B — Hinge Focus',
      type: 'lift',
      exercises: [
        { exerciseId: 'deadlift',        name: 'Conventional Deadlift', sets: 4, reps: '5–6',  rest: 180, isKPI: true, notes: 'Belt and straps on working sets. Speed off the floor.' },
        { exerciseId: 'hack-squat',      name: 'Hack Squat / Belt Squat',sets: 3,reps: '10–12', rest: 90, notes: 'Knee track over toes. Full depth.' },
        { exerciseId: 'leg-ext',         name: 'Leg Extension',         sets: 3, reps: '15–20', rest: 60, notes: 'Squeeze at top. Controlled negative.' },
        { exerciseId: 'nordic-curl',     name: 'Nordic Curl / Leg Curl',sets: 3, reps: '8–10', rest: 75, notes: 'Eccentric focus. Very slow lowering.' },
        { exerciseId: 'calf-seated',     name: 'Seated Calf Raise',     sets: 4, reps: '15–20', rest: 45, notes: 'Soleus focus. Slow and full range.' },
      ],
      notes: 'Hinge-dominant lower. Primary hamstring and posterior chain.',
    },
    {
      dayNumber: 6,
      name: 'Rest',
      type: 'recovery',
      mobility: ['full body mobility', 'foam roll'],
      notes: 'Full rest. Walk if desired. Eat to target.',
    },
    {
      dayNumber: 7,
      name: 'Rest',
      type: 'recovery',
      mobility: ['light stretch'],
      notes: 'Full rest. Prep for the next week.',
    },
  ],
  kpis: [
    { exercise: 'Barbell Bench Press',   metric: 'load x reps', days: [1] },
    { exercise: 'Barbell Back Squat',    metric: 'load x reps', days: [2] },
    { exercise: 'Weighted Pull-Up',      metric: 'load x reps', days: [4] },
    { exercise: 'Conventional Deadlift', metric: 'load x reps', days: [5] },
  ],
  progressionRule: 'Double progression: add reps until top of range is hit across all sets, then add load next session. Deload week every 4–6 weeks.',
  volumeTracking: {
    chest:      { setsPerCycle: 13, setsPerWeek: 13, status: 'at target' },
    back:       { setsPerCycle: 13, setsPerWeek: 13, status: 'at target' },
    quads:      { setsPerCycle: 13, setsPerWeek: 13, status: 'at target' },
    hamstrings: { setsPerCycle: 10, setsPerWeek: 10, status: 'at target' },
    delts:      { setsPerCycle: 10, setsPerWeek: 10, status: 'at target' },
    biceps:     { setsPerCycle: 9,  setsPerWeek: 9,  status: 'at target' },
    triceps:    { setsPerCycle: 6,  setsPerWeek: 6,  status: 'minimum effective' },
  },
};
