import type { Program } from '@/lib/types';

export const fezProgram: Omit<Program, 'id'> = {
  name: 'Fez — Early AM Hypertrophy + Cardio Maintenance',
  cycleLengthDays: 7,
  splitType: 'Upper / Lower + Cardio',
  isActive: true,
  startDate: new Date().toISOString().split('T')[0],
  sessions: [
    {
      dayNumber: 1,
      name: 'Upper — Shoulder-Safe Pressing',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'landmine-press',
          name: 'Landmine Press',
          sets: 4,
          reps: '8–10',
          rest: 90,
          isKPI: true,
          notes: 'Neutral path; stop before sharp pin-site pain.',
        },
        {
          exerciseId: 'neutral-machine-press',
          name: 'Neutral Machine Chest Press',
          sets: 3,
          reps: '10–12',
          rest: 75,
          notes: 'Squeeze mid-range; no flare past comfortable ROM.',
        },
        {
          exerciseId: 'seated-cable-row',
          name: 'Seated Cable Row',
          sets: 4,
          reps: '10–12',
          rest: 75,
          notes: 'Thoracic extension; full stretch each rep.',
        },
        {
          exerciseId: 'lat-pulldown',
          name: 'Lat Pulldown',
          sets: 3,
          reps: '12–15',
          rest: 60,
          notes: 'Slight lean, elbows track to hip pockets.',
        },
        {
          exerciseId: 'face-pull',
          name: 'Face Pull',
          sets: 3,
          reps: '15–20',
          rest: 45,
          notes: 'External rotation finish every rep.',
        },
        {
          exerciseId: 'tricep-pushdown',
          name: 'Tricep Pushdown',
          sets: 3,
          reps: '12–15',
          rest: 45,
          notes: 'Elbows pinned; full extension without snap.',
        },
      ],
      mobility: ['shoulders', 't-spine'],
      notes: 'Commercial gym A.M. block — log overhead tolerance 1–5 after session.',
    },
    {
      dayNumber: 2,
      name: 'Lower — Quad + Posterior',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'leg-press',
          name: 'Leg Press',
          sets: 4,
          reps: '10–12',
          rest: 120,
          isKPI: true,
          notes: 'Full ROM; feet where knee tracks stays happy.',
        },
        {
          exerciseId: 'romanian-dl',
          name: 'Romanian Deadlift',
          sets: 3,
          reps: '10–12',
          rest: 90,
          notes: 'Hamstring bias; controlled lowering.',
        },
        {
          exerciseId: 'leg-curl',
          name: 'Lying Leg Curl',
          sets: 3,
          reps: '12–15',
          rest: 60,
          notes: 'Pause peak contraction.',
        },
        {
          exerciseId: 'calf-raise',
          name: 'Standing Calf Raise',
          sets: 4,
          reps: '15–20',
          rest: 45,
          notes: 'Slow eccentrics for surf-specific calves.',
        },
      ],
      mobility: ['ankles', 'hips'],
      notes: 'Lower body tolerates heavier loads — progress here while shoulder recalibrates.',
    },
    {
      dayNumber: 3,
      name: 'Cardio — Intervals',
      type: 'cardio',
      cardio: {
        type: 'Bike or rower',
        duration: 35,
        intervals: { work: 1, rest: 1, rounds: 10 },
        note: 'Moderate-hard efforts; nasal breathing in warm-up.',
      },
      mobility: ['hips'],
      notes: 'Maintain engine for bodyboard heats without trashing shoulders.',
    },
    {
      dayNumber: 4,
      name: 'Upper — Pull + Arms',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'weighted-pullup',
          name: 'Neutral Grip Pull-Up',
          sets: 4,
          reps: '6–10',
          rest: 120,
          isKPI: true,
          notes: 'Add load or band-assist as needed; no kip.',
        },
        {
          exerciseId: 'one-arm-row',
          name: 'Single Arm Cable Row',
          sets: 3,
          reps: '12/side',
          rest: 60,
          notes: 'Brace core; no torso rotation.',
        },
        {
          exerciseId: 'incline-db',
          name: 'Low Incline DB Press',
          sets: 3,
          reps: '10–12',
          rest: 75,
          notes: 'Short ROM if shoulder cranky — quality over ego.',
        },
        {
          exerciseId: 'lateral-raise',
          name: 'Lateral Raise',
          sets: 4,
          reps: '15–20',
          rest: 45,
          notes: 'Lead with elbows; light load.',
        },
        {
          exerciseId: 'hammer-curl',
          name: 'Hammer Curl',
          sets: 3,
          reps: '12–15',
          rest: 45,
          notes: '',
        },
      ],
      mobility: ['shoulders', 'lats'],
      notes: 'Second upper day — bias pulling volume.',
    },
    {
      dayNumber: 5,
      name: 'Lower — Hinge + Accessories',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'hack-squat',
          name: 'Hack Squat',
          sets: 4,
          reps: '10–12',
          rest: 90,
          isKPI: true,
          notes: 'Depth you own; smooth reps.',
        },
        {
          exerciseId: 'leg-ext',
          name: 'Leg Extension',
          sets: 3,
          reps: '15–20',
          rest: 60,
          notes: 'Quad pump finisher.',
        },
        {
          exerciseId: 'nordic-curl',
          name: 'Nordic Curl',
          sets: 3,
          reps: '6–8',
          rest: 75,
          notes: 'Eccentric emphasis.',
        },
        {
          exerciseId: 'plank',
          name: 'Plank Hold',
          sets: 3,
          reps: '45s',
          rest: 45,
          notes: 'Ribs down; breathe behind brace.',
        },
      ],
      mobility: ['hamstrings', 'hips'],
      notes: '',
    },
    {
      dayNumber: 6,
      name: 'Active Recovery / Swim',
      type: 'cardio',
      cardio: { type: 'Easy swim or walk', duration: 40, note: 'Shoulder-friendly strokes only.' },
      mobility: ['full body'],
      notes: 'Optional — skip if work or travel; no guilt.',
    },
    {
      dayNumber: 7,
      name: 'Rest',
      type: 'recovery',
      mobility: ['light stretch'],
      notes: 'Food prep for the week; sleep priority.',
    },
  ],
  kpis: [
    { exercise: 'Landmine Press', metric: 'load x reps', days: [1] },
    { exercise: 'Leg Press', metric: 'load x reps', days: [2] },
    { exercise: 'Neutral Grip Pull-Up', metric: 'load x reps', days: [4] },
    { exercise: 'Hack Squat', metric: 'load x reps', days: [5] },
  ],
  progressionRule:
    'Add reps in range before load. If shoulder symptom >3/10 next morning, reduce pressing ROM and volume for one week.',
  volumeTracking: {
    chest: { setsPerCycle: 12, setsPerWeek: 12, status: 'at target' },
    back: { setsPerCycle: 14, setsPerWeek: 14, status: 'at target' },
    quads: { setsPerCycle: 14, setsPerWeek: 14, status: 'at target' },
    hamstrings: { setsPerCycle: 9, setsPerWeek: 9, status: 'at target' },
    delts: { setsPerCycle: 10, setsPerWeek: 10, status: 'at target' },
    biceps: { setsPerCycle: 3, setsPerWeek: 3, status: 'below minimum' },
    triceps: { setsPerCycle: 6, setsPerWeek: 6, status: 'at target' },
    calves: { setsPerCycle: 8, setsPerWeek: 8, status: 'at target' },
  },
};
