import type { Program } from '@/lib/types';

export const jordanProgram: Omit<Program, 'id'> = {
  name: 'Jordan 3-Day Full Body Foundation',
  cycleLengthDays: 7,
  splitType: 'Full Body (3×/week)',
  isActive: true,
  startDate: new Date().toISOString().split('T')[0],
  sessions: [
    {
      dayNumber: 1,
      name: 'Full Body A',
      type: 'lift',
      exercises: [
        { exerciseId: 'goblet-squat',    name: 'Goblet Squat',        sets: 3, reps: '10–12', rest: 75, isKPI: true, notes: 'Focus on depth and knee tracking. Use comfortable load.' },
        { exerciseId: 'db-bench',        name: 'DB Bench Press',      sets: 3, reps: '10–12', rest: 75, isKPI: true, notes: 'Controlled press. Pause briefly at chest.' },
        { exerciseId: 'cable-row',       name: 'Seated Cable Row',    sets: 3, reps: '12',    rest: 60, notes: 'Drive elbows back. Full stretch at front.' },
        { exerciseId: 'hip-hinge',       name: 'DB Romanian Deadlift',sets: 3, reps: '12',    rest: 75, notes: 'Hinge, don\'t squat. Feel hamstring tension.' },
        { exerciseId: 'plank',           name: 'Plank Hold',          sets: 3, reps: '30s',   rest: 45, notes: 'Neutral spine. Breathe through it.' },
      ],
      mobility: ['hips', 'thoracic spine'],
      notes: 'Focus on movement quality. Leave 3+ reps in reserve on all sets.',
    },
    {
      dayNumber: 2,
      name: 'Rest / Walk',
      type: 'cardio',
      cardio: { type: 'Walk', duration: 30, note: 'Aim for 7,000–10,000 steps today. Easy pace.' },
      mobility: ['hips', 'lower back'],
      notes: 'Active rest — a walk counts.',
    },
    {
      dayNumber: 3,
      name: 'Full Body B',
      type: 'lift',
      exercises: [
        { exerciseId: 'split-squat',     name: 'Split Squat',         sets: 3, reps: '10/leg', rest: 75, isKPI: true, notes: 'Front foot flat, back knee to floor. Bodyweight or light DBs.' },
        { exerciseId: 'incline-db',      name: 'Incline DB Press',    sets: 3, reps: '10–12', rest: 75, notes: 'Slight incline. Control the descent.' },
        { exerciseId: 'lat-pulldown',    name: 'Lat Pulldown',        sets: 3, reps: '12',    rest: 60, notes: 'Pull to upper chest. Don\'t lean back excessively.' },
        { exerciseId: 'hip-thrust',      name: 'Hip Thrust (BW/DB)',  sets: 3, reps: '15',    rest: 60, notes: 'Squeeze glutes at top. Full hip extension.' },
        { exerciseId: 'dead-bug',        name: 'Dead Bug',            sets: 3, reps: '8/side', rest: 45, notes: 'Lower back flat on floor throughout.' },
      ],
      mobility: ['glutes', 'ankles'],
      notes: 'Unilateral focus today. Good for addressing imbalances.',
    },
    {
      dayNumber: 4,
      name: 'Rest',
      type: 'recovery',
      mobility: ['full body stretch', 'foam roll'],
      notes: 'Rest or light walk. Prioritise sleep tonight.',
    },
    {
      dayNumber: 5,
      name: 'Full Body C',
      type: 'lift',
      exercises: [
        { exerciseId: 'leg-press',       name: 'Leg Press',           sets: 3, reps: '12–15', rest: 75, notes: 'Feet shoulder-width. Full range of motion.' },
        { exerciseId: 'db-ohp',          name: 'DB Shoulder Press',   sets: 3, reps: '10–12', rest: 75, isKPI: true, notes: 'Seated. Press straight overhead, full extension.' },
        { exerciseId: 'one-arm-row',     name: 'Single Arm DB Row',   sets: 3, reps: '12/side', rest: 60, notes: 'Stable position. Full row.' },
        { exerciseId: 'glute-bridge',    name: 'Glute Bridge',        sets: 3, reps: '15',    rest: 60, notes: 'Bodyweight or with plate. Squeeze hard at top.' },
        { exerciseId: 'bird-dog',        name: 'Bird Dog',            sets: 3, reps: '10/side', rest: 45, notes: 'Slow and controlled. Don\'t let hips rotate.' },
      ],
      mobility: ['shoulders', 'hips'],
      notes: 'Third session — a little more variety. Note how your body is feeling vs Monday.',
    },
    {
      dayNumber: 6,
      name: 'Active Recovery',
      type: 'cardio',
      cardio: { type: 'Walk or light yoga', duration: 30, note: 'Easy movement. No intensity required.' },
      breathWork: [
        { name: 'Diaphragmatic Breathing', inhale: 4, hold: 0, exhale: 6, holdOut: 0, rounds: 8 },
      ],
      mobility: ['full body', 'spinal rotation'],
    },
    {
      dayNumber: 7,
      name: 'Rest',
      type: 'recovery',
      mobility: ['light stretch'],
      notes: 'Full rest. Prepare meals for the week if possible.',
    },
  ],
  kpis: [
    { exercise: 'Goblet Squat',      metric: 'load x reps', days: [1] },
    { exercise: 'DB Bench Press',    metric: 'load x reps', days: [1] },
    { exercise: 'Split Squat',       metric: 'load x reps', days: [3] },
    { exercise: 'DB Shoulder Press', metric: 'load x reps', days: [5] },
  ],
  progressionRule: 'Focus on form for first 2 weeks. Add reps before adding load. Increase load only when all sets are completed comfortably with good technique.',
  volumeTracking: {
    chest:      { setsPerCycle: 9,  setsPerWeek: 9,  status: 'at target' },
    back:       { setsPerCycle: 9,  setsPerWeek: 9,  status: 'at target' },
    quads:      { setsPerCycle: 9,  setsPerWeek: 9,  status: 'at target' },
    hamstrings: { setsPerCycle: 6,  setsPerWeek: 6,  status: 'minimum effective' },
    delts:      { setsPerCycle: 6,  setsPerWeek: 6,  status: 'at target' },
    biceps:     { setsPerCycle: 0,  setsPerWeek: 0,  status: 'below minimum' },
    triceps:    { setsPerCycle: 0,  setsPerWeek: 0,  status: 'below minimum' },
  },
};
