import type { Program } from '@/lib/types';

export const mariaProgram: Omit<Program, 'id'> = {
  name: 'Maria — Home, Pool & Stairs',
  cycleLengthDays: 7,
  splitType: 'Hybrid (3× strength + cardio)',
  isActive: true,
  startDate: new Date().toISOString().split('T')[0],
  sessions: [
    {
      dayNumber: 1,
      name: 'Full Body A — Home',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'goblet-squat',
          name: 'Goblet Squat',
          sets: 3,
          reps: '12–15',
          rest: 60,
          isKPI: true,
          notes: 'Backpack loaded if needed; depth you own.',
        },
        {
          exerciseId: 'push-up',
          name: 'Push-Up (incline if needed)',
          sets: 3,
          reps: '8–15',
          rest: 60,
          isKPI: true,
          notes: 'Hands on bench or counter on tired weeks.',
        },
        {
          exerciseId: 'split-squat',
          name: 'Split Squat',
          sets: 3,
          reps: '10/leg',
          rest: 60,
          notes: 'Light DB or water bottles optional.',
        },
        {
          exerciseId: 'plank',
          name: 'Plank Hold',
          sets: 3,
          reps: '30–45s',
          rest: 45,
          notes: '',
        },
      ],
      mobility: ['hips', 'wrists'],
      notes:
        '“Big kid week” option — stack this day with Tue/Wed when you have three straight windows.',
    },
    {
      dayNumber: 2,
      name: 'Pool + Core',
      type: 'cardio',
      cardio: {
        type: 'Pool laps + treading',
        duration: 30,
        note: 'Easy to moderate; add 4×25m pickups if feeling good.',
      },
      coreWork: [{ name: 'Dead Bug', sets: 3, reps: 8, perSide: true, prolapseSafe: true }],
      mobility: ['shoulders', 'thoracic spine'],
      notes: 'Low joint stress — use after stairs if knees need a break.',
    },
    {
      dayNumber: 3,
      name: 'Hill Stairs + Walk',
      type: 'cardio',
      cardio: {
        type: 'Hill stairs + flat walk',
        duration: 35,
        note: '6–10 stair repeats easy-moderate; finish with 10 min flat walk.',
      },
      mobility: ['calves', 'quads'],
      notes: 'Stop if knee fronts get sharp — shorten step height.',
    },
    {
      dayNumber: 4,
      name: 'Rest / Light walk',
      type: 'recovery',
      mobility: ['full body stretch'],
      notes: 'Kid-friendly day — a family walk counts.',
    },
    {
      dayNumber: 5,
      name: 'Full Body B — Home',
      type: 'lift',
      exercises: [
        {
          exerciseId: 'hip-thrust',
          name: 'Hip Thrust (bench + band)',
          sets: 3,
          reps: '12–18',
          rest: 75,
          isKPI: true,
          notes: 'Pause 1s at top.',
        },
        {
          exerciseId: 'inverted-row',
          name: 'Inverted Row (table/rack)',
          sets: 3,
          reps: '8–12',
          rest: 60,
          notes: 'Body angle adjusts difficulty.',
        },
        {
          exerciseId: 'lunge',
          name: 'Reverse Lunge',
          sets: 3,
          reps: '10/leg',
          rest: 60,
          notes: 'Hold wall if balance is the limiter.',
        },
        {
          exerciseId: 'side-plank',
          name: 'Side Plank',
          sets: 2,
          reps: '25s/side',
          rest: 45,
          notes: '',
        },
      ],
      mobility: ['glutes', 'lats'],
      notes: 'Short session template (~35 min) for custody handoff days.',
    },
    {
      dayNumber: 6,
      name: 'Pool recovery swim',
      type: 'cardio',
      cardio: { type: 'Easy swim', duration: 25, note: 'Conversational pace.' },
      mobility: ['hips'],
      notes: '',
    },
    {
      dayNumber: 7,
      name: 'Rest',
      type: 'recovery',
      mobility: ['light stretch'],
      notes: 'Prep simple proteins for the week ahead.',
    },
  ],
  kpis: [
    { exercise: 'Goblet Squat', metric: 'load x reps', days: [1] },
    { exercise: 'Push-Up (incline if needed)', metric: 'reps', days: [1] },
    { exercise: 'Hip Thrust (bench + band)', metric: 'reps', days: [5] },
  ],
  progressionRule:
    'Add reps or a little backpack load before shortening rest. On kid-heavy weeks, maintain is a win.',
  volumeTracking: {
    chest: { setsPerCycle: 6, setsPerWeek: 6, status: 'minimum effective' },
    back: { setsPerCycle: 6, setsPerWeek: 6, status: 'minimum effective' },
    quads: { setsPerCycle: 9, setsPerWeek: 9, status: 'at target' },
    hamstrings: { setsPerCycle: 6, setsPerWeek: 6, status: 'minimum effective' },
    delts: { setsPerCycle: 0, setsPerWeek: 0, status: 'below minimum' },
    biceps: { setsPerCycle: 0, setsPerWeek: 0, status: 'below minimum' },
    triceps: { setsPerCycle: 3, setsPerWeek: 3, status: 'below minimum' },
    calves: { setsPerCycle: 3, setsPerWeek: 3, status: 'below minimum' },
  },
};
