import type { Program } from '@/lib/types';

export const morganProgram: Omit<Program, 'id'> = {
  name: 'Rebuild Block 1',
  cycleLengthDays: 14,
  splitType: 'rotating-14',
  isActive: true,
  startDate: new Date().toISOString().split('T')[0],
  sessions: [
    {
      dayNumber: 1,
      name: 'Delts / Tris',
      type: 'lift',
      exercises: [
        { exerciseId: 'seated-db-ohp', name: 'Seated DB OHP', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'lateral-raise', name: 'Lateral Raise', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'rear-delt-flye', name: 'Rear Delt Flye', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'shrug', name: 'Shrug', sets: 3, reps: 12, rest: 60 },
        { exerciseId: 'close-grip-bench', name: 'Close Grip Bench', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'oh-extension', name: 'OH Extension', sets: 2, reps: 12, rest: 60 },
      ],
      notes: 'If incline press stalls on Day 5 or front delts feel fried, drop Lateral Raise to 1 set before adjusting chest programming.',
    },
    {
      dayNumber: 2,
      name: 'Cardio / Breath / Abs',
      type: 'cardio',
      cardio: { type: 'brisk-walk', duration: 25, note: 'talking pace' },
      breathWork: [
        { name: '4-2-6', inhale: 4, hold: 2, exhale: 6, rounds: 5 },
        { name: 'Box Breathing', inhale: 4, hold: 4, exhale: 4, holdOut: 4, rounds: 5 },
      ],
      coreWork: [
        { name: 'Dead Bug', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
        { name: 'Side Plank', sets: 3, holdSec: 20, perSide: true, prolapseSafe: true },
        { name: 'Pallof Press', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
      ],
      mobility: ['Thoracic rotations 2 min', 'Hip openers 3 min'],
    },
    {
      dayNumber: 3,
      name: 'Back',
      type: 'lift',
      exercises: [
        { exerciseId: 'pull-ups', name: 'Pull-ups', sets: 3, reps: '6-10', rest: 75, isKPI: true },
        { exerciseId: 'meadows-row', name: 'Meadows Row', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'chest-supported-row', name: 'Chest Supported Row', sets: 2, reps: 12, rest: 75 },
        { exerciseId: 'rear-delt-flye', name: 'Rear Delt Flye', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'shrug', name: 'Shrug', sets: 2, reps: 15, rest: 45 },
      ],
    },
    {
      dayNumber: 4,
      name: 'Cardio / Breath / Abs',
      type: 'cardio',
      cardio: { type: 'brisk-walk-intervals', duration: 25, note: '1 min brisk + 1 min easy x10 rounds' },
      breathWork: [
        { name: 'Extended Exhale', inhale: 4, exhale: 8, rounds: 10 },
      ],
      coreWork: [
        { name: 'Reverse Crunch', sets: 3, reps: 15, perSide: false, prolapseSafe: true },
        { name: 'Side Plank', sets: 3, holdSec: 20, perSide: true, prolapseSafe: true },
        { name: 'Dead Bug', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
      ],
      mobility: ['Hip openers 3 min'],
    },
    {
      dayNumber: 5,
      name: 'Chest / Biceps',
      type: 'lift',
      exercises: [
        { exerciseId: 'db-bench', name: 'DB Bench', sets: 3, reps: 8, rest: 90, isKPI: true },
        { exerciseId: 'incline-db-press', name: 'Incline DB Press', sets: 3, reps: 10, rest: 75 },
        { exerciseId: 'decline-press', name: 'Decline Press', sets: 2, reps: 12, rest: 75 },
        { exerciseId: 'cable-flye', name: 'Cable Flye / Pec Deck', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'bb-curl', name: 'BB Curl', sets: 2, reps: 10, rest: 60 },
        { exerciseId: 'hammer-curl', name: 'Hammer Curl', sets: 2, reps: 12, rest: 45 },
      ],
    },
    {
      dayNumber: 6,
      name: 'Cardio / Breath / Core + Quad Top-Up',
      type: 'cardio',
      cardio: { type: 'brisk-walk', duration: 30, note: 'Every 5 min: 30 sec faster pace' },
      breathWork: [
        { name: 'Cadence Walking', inhale: 3, exhale: 4, rounds: 1 },
      ],
      coreWork: [
        { name: 'Pallof Press', sets: 3, reps: 12, perSide: true, prolapseSafe: true },
        { name: 'Side Plank', sets: 3, holdSec: 30, perSide: true, prolapseSafe: true },
        { name: 'Bird Dog', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
      ],
      notes: 'Quad Top-Up: Sissy Squat 2x15 (bodyweight, controlled tempo)',
    },
    {
      dayNumber: 7,
      name: 'Legs',
      type: 'lift',
      exercises: [
        { exerciseId: 'walking-lunge', name: 'Walking Lunge', sets: 3, reps: '8/leg', rest: 90, isKPI: true },
        { exerciseId: 'sissy-squat', name: 'Sissy Squat', sets: 3, reps: 12, rest: 75 },
        { exerciseId: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', sets: 2, reps: 12, rest: 75 },
        { exerciseId: 'nordic-curl', name: 'Nordic Curl', sets: 2, reps: 6, rest: 90 },
        { exerciseId: 'floor-slide-curl', name: 'Floor Slide Curl', sets: 2, reps: 15, rest: 60 },
      ],
    },
    {
      dayNumber: 8,
      name: 'Cardio / Breath / Core',
      type: 'cardio',
      cardio: { type: 'brisk-walk', duration: 35, note: '5 x 20 sec fast pace bursts' },
      breathWork: [
        { name: '4-2-6', inhale: 4, hold: 2, exhale: 6, rounds: 8 },
      ],
      coreWork: [
        { name: 'Dead Bug', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
        { name: 'Side Plank', sets: 3, holdSec: 20, perSide: true, prolapseSafe: true },
        { name: 'Pallof Press', sets: 3, reps: 10, perSide: true, prolapseSafe: true },
      ],
    },
    {
      dayNumber: 9,
      name: 'Delts / Tris',
      type: 'lift',
      exercises: [
        { exerciseId: 'seated-db-ohp', name: 'Seated DB OHP', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'lateral-raise', name: 'Lateral Raise', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'rear-delt-flye', name: 'Rear Delt Flye', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'shrug', name: 'Shrug', sets: 3, reps: 12, rest: 60 },
        { exerciseId: 'close-grip-bench', name: 'Close Grip Bench', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'oh-extension', name: 'OH Extension', sets: 2, reps: 12, rest: 60 },
      ],
      notes: 'Progression: Beat Week 1 by +1 rep per set OR +1-2.5kg, not both.',
    },
    {
      dayNumber: 10,
      name: 'Cardio / Interval Progression',
      type: 'cardio',
      cardio: { type: 'brisk-walk-intervals', duration: 30, note: '90 sec brisk + 60 sec easy x8 rounds' },
      breathWork: [
        { name: 'Box Breathing', inhale: 4, hold: 4, exhale: 4, holdOut: 4, rounds: 6 },
      ],
      coreWork: [
        { name: 'Bird Dog', sets: 2, reps: 10, perSide: true, prolapseSafe: true },
        { name: 'Side Plank', sets: 2, holdSec: 25, perSide: true, prolapseSafe: true },
        { name: 'Dead Bug', sets: 2, reps: 10, perSide: true, prolapseSafe: true },
      ],
    },
    {
      dayNumber: 11,
      name: 'Back',
      type: 'lift',
      exercises: [
        { exerciseId: 'pull-ups', name: 'Pull-ups', sets: 3, reps: '6-10', rest: 75, isKPI: true },
        { exerciseId: 't-bar-row', name: 'T-Bar Row', sets: 3, reps: 8, rest: 90 },
        { exerciseId: 'chest-supported-row', name: 'Chest Supported Row', sets: 2, reps: 12, rest: 75 },
        { exerciseId: 'rear-delt-flye', name: 'Rear Delt Flye', sets: 2, reps: 15, rest: 45 },
        { exerciseId: 'shrug', name: 'Shrug', sets: 2, reps: 15, rest: 45 },
      ],
      notes: 'Use T-Bar Row instead of Meadows Row.',
    },
    {
      dayNumber: 12,
      name: 'Recovery Conditioning',
      type: 'cardio',
      cardio: { type: 'easy-walk', duration: 40, note: 'conversational pace' },
      breathWork: [
        { name: 'Resonance Breathing', inhale: 5, exhale: 5, rounds: 10 },
      ],
      coreWork: [
        { name: 'Bird Dog', sets: 2, reps: 10, perSide: true, prolapseSafe: true },
        { name: 'Plank', sets: 2, holdSec: 30, perSide: false, prolapseSafe: true },
      ],
    },
    {
      dayNumber: 13,
      name: 'Chest / Biceps + Legs Pump',
      type: 'lift',
      exercises: [
        { exerciseId: 'db-bench', name: 'DB Bench', sets: 3, reps: 8, rest: 90, isKPI: true, notes: 'Beat Day 5 KPI' },
        { exerciseId: 'incline-db-press', name: 'Incline Press', sets: 2, reps: 12, rest: 75 },
        { exerciseId: 'bb-curl', name: 'BB Curl', sets: 2, reps: 10, rest: 60 },
        { exerciseId: 'walking-lunge', name: 'Walking Lunge', sets: 2, reps: '12/leg', rest: 75 },
        { exerciseId: 'floor-slide-curl', name: 'Floor Slide Curl', sets: 2, reps: 20, rest: 45 },
        { exerciseId: 'standing-calf-raise', name: 'Standing Calf Raise', sets: 3, reps: 20, rest: 45 },
      ],
      notes: 'Fatigue flag: As loads increase over 4-6 weeks, this session risks junk volume. When that happens, either split into two sessions or drop one element (calves or curls).',
    },
    {
      dayNumber: 14,
      name: 'Full Recovery',
      type: 'recovery',
      cardio: { type: 'rest-walk', duration: 0, note: 'Steps: 6000-8000' },
      notes: 'Stretching: 10 min. Relaxation: High. Complete rest from training.',
    },
  ],
  kpis: [
    { exercise: 'DB Bench', metric: 'load x reps, best set', days: [5, 13] },
    { exercise: 'Pull-ups', metric: 'total reps across 3 sets', days: [3, 11] },
    { exercise: 'Walking Lunge', metric: 'load x reps/leg, best set', days: [7, 13] },
  ],
  progressionRule: 'Beat Week 1 by +1 rep per set OR +1-2.5kg, not both. If neither happens, repeat the same numbers.',
  volumeTracking: {
    chest: { setsPerCycle: 15, setsPerWeek: 7.5, status: 'Intro-adequate; push to 10-12/wk by block 3' },
    back: { setsPerCycle: 22, setsPerWeek: 11, status: 'Good; track pull-up total reps as KPI' },
    quads: { setsPerCycle: 12, setsPerWeek: 6, status: 'Improved; reassess after 2 cycles' },
    delts: { setsPerCycle: 14, setsPerWeek: 7, status: 'Adequate for a strength, no increase needed' },
    hamstrings: { setsPerCycle: 6, setsPerWeek: 3, status: 'Monitor; add volume if recovery allows' },
  },
};
