'use client';

import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/stores';
import { useProfile, useUpdateProfile } from '@/controllers';
import { logout } from '@/lib/firebase';
import { Settings, Upload, User, LogOut, Target } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

export default function SettingsPage() {
  const router = useRouter();
  const { user } = useAuthStore();
  const userId = user?.uid ?? '';

  const { data: profile } = useProfile(userId);
  const { mutate: updateProfile, isPending } = useUpdateProfile(userId);

  const [targetWeight, setTargetWeight] = useState('');
  const [currentWeight, setCurrentWeight] = useState('');

  const handleSaveWeights = () => {
    const updates: Record<string, number> = {};
    if (targetWeight) updates.targetWeight = parseFloat(targetWeight);
    if (currentWeight) updates.currentWeight = parseFloat(currentWeight);
    if (Object.keys(updates).length === 0) return;

    updateProfile(updates, {
      onSuccess: () => {
        toast.success('Profile updated.');
        setTargetWeight('');
        setCurrentWeight('');
      },
      onError: (e) => toast.error(`Failed: ${e.message}`),
    });
  };

  const handleLogout = async () => {
    await logout();
    router.push('/login');
  };

  return (
    <div className="space-y-6 max-w-lg">
      <div>
        <h1 className="text-2xl font-bold text-[#F5F5F5]">Settings</h1>
        <p className="text-[#6B6B6B]">Manage your profile and plan</p>
      </div>

      {/* Profile */}
      <div className="glass-panel p-5 space-y-4">
        <div className="flex items-center gap-3">
          <User size={20} className="text-[#6B6B6B]" />
          <h2 className="font-semibold text-[#F5F5F5]">Profile</h2>
        </div>

        <div className="space-y-1">
          <p className="text-xs text-[#6B6B6B]">Email</p>
          <p className="text-[#F5F5F5]">{user?.email}</p>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1">
            <p className="text-xs text-[#6B6B6B]">Current Weight</p>
            <p className="font-mono tabular-nums text-[#F5F5F5]">{profile?.currentWeight ?? '—'} kg</p>
          </div>
          <div className="space-y-1">
            <p className="text-xs text-[#6B6B6B]">Target Weight</p>
            <p className="font-mono tabular-nums text-[#F5F5F5]">{profile?.targetWeight ?? '—'} kg</p>
          </div>
        </div>
      </div>

      {/* Update weights */}
      <div className="glass-panel p-5 space-y-4">
        <div className="flex items-center gap-3">
          <Target size={20} className="text-[#DC2626]" />
          <h2 className="font-semibold text-[#F5F5F5]">Update Weights</h2>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1">
            <label className="text-xs text-[#6B6B6B]">Current (kg)</label>
            <input
              type="number"
              step="0.1"
              value={currentWeight}
              onChange={e => setCurrentWeight(e.target.value)}
              placeholder={profile?.currentWeight?.toString() ?? ''}
              className="w-full bg-[rgba(16,22,34,0.6)] border border-[rgba(80,96,128,0.25)] rounded-lg p-3 text-[#F5F5F5] placeholder:text-[#6B6B6B]/50 focus:outline-none focus:border-[rgba(212,175,55,0.4)]"
            />
          </div>
          <div className="space-y-1">
            <label className="text-xs text-[#6B6B6B]">Target (kg)</label>
            <input
              type="number"
              step="0.1"
              value={targetWeight}
              onChange={e => setTargetWeight(e.target.value)}
              placeholder={profile?.targetWeight?.toString() ?? ''}
              className="w-full bg-[rgba(16,22,34,0.6)] border border-[rgba(80,96,128,0.25)] rounded-lg p-3 text-[#F5F5F5] placeholder:text-[#6B6B6B]/50 focus:outline-none focus:border-[rgba(212,175,55,0.4)]"
            />
          </div>
        </div>

        <button
          onClick={handleSaveWeights}
          disabled={isPending || (!targetWeight && !currentWeight)}
          className="btn-primary w-full disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {isPending ? 'Saving…' : 'Save'}
        </button>
      </div>

      {/* Re-import plan */}
      <div className="glass-panel p-5 space-y-4">
        <div className="flex items-center gap-3">
          <Upload size={20} className="text-[#DC2626]" />
          <h2 className="font-semibold text-[#F5F5F5]">Re-import Plan</h2>
        </div>
        <p className="text-sm text-[#6B6B6B]">
          Upload new JSON files generated by your coach AI to update your training plan, nutrition targets, or volume landmarks.
          If you already have data in IronMind, open the review step and check{' '}
          <span className="text-[#9A9A9A]">Replace existing IronMind data</span> before confirming import.
        </p>
        <button
          onClick={() => router.push('/onboarding')}
          className="btn-secondary w-full flex items-center justify-center gap-2"
        >
          <Upload size={16} /> Import Coach Files
        </button>
      </div>

      {/* Sign out */}
      <div className="glass-panel p-5">
        <div className="flex items-center gap-3 mb-4">
          <Settings size={20} className="text-[#6B6B6B]" />
          <h2 className="font-semibold text-[#F5F5F5]">Account</h2>
        </div>
        <button
          onClick={handleLogout}
          className="w-full py-2.5 bg-[rgba(239,68,68,0.12)] border border-[rgba(239,68,68,0.3)] text-[#EF4444] font-medium rounded-lg hover:bg-[rgba(239,68,68,0.2)] transition-colors flex items-center justify-center gap-2"
        >
          <LogOut size={18} /> Sign Out
        </button>
      </div>
    </div>
  );
}
